name: Deno Test

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '.github/workflows/deno-test.yml'
      - 'deno.jsonc'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno task lint

      - name: Get Denops
        run: |
          git clone https://github.com/vim-denops/denops.vim
          echo "DENOPS_TEST_DENOPS_PATH=${PWD}/denops.vim" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: vim

      - name: Export Vim Executable
        run: |
          echo "DENOPS_TEST_VIM_EXECUTABLE=${{ steps.vim.outputs.executable }}" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true

      - name: Export Neovim Executable
        run: |
          echo "DENOPS_TEST_NVIM_EXECUTABLE=${{ steps.nvim.outputs.executable }}" >> "$GITHUB_ENV"

      - name: Run tests
        run: deno task test
