# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deno Test

on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - ".github/workflows/deno-test.yml"
      - "deno.jsonc"
  pull_request:
    branches:
      - main
    paths:
      - "**.ts"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Check
        run: deno task check

      - name: Run linter
        run: deno task lint

      - name: Get Denops
        run: |
          git clone https://github.com/vim-denops/denops.vim /tmp/denops.vim
          echo "DENOPS_TEST_DENOPS_PATH=/tmp/denops.vim" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: v9.1.0400

      - name: Export Vim Executable
        run: |
          echo "DENOPS_TEST_VIM_EXECUTABLE=${{ steps.vim.outputs.executable }}" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true

      - name: Export Neovim Executable
        run: |
          echo "DENOPS_TEST_NVIM_EXECUTABLE=${{ steps.nvim.outputs.executable }}" >> "$GITHUB_ENV"

      - name: Run tests
        run: deno task test
